import { levelToSeverity, rules } from 'legion-rules';
import type { LegionConfig, Level } from 'legion-rules';

export const START = '<!-- legion-steer:start -->';
export const END = '<!-- legion-steer:end -->';

const LEVEL_NOTE: Record<Level, string> = {
  0: 'off',
  1: 'warn',
  2: 'error, a scoped and explained disable is honored',
  3: 'error and locked, a disable naming it is itself a violation',
};

const isLegionRule = (name: string): name is keyof typeof rules =>
  Object.hasOwn(rules, name);

const ruleLine = (name: string, level: Level): string => {
  if (!isLegionRule(name)) return `- \`${name}\` — ${LEVEL_NOTE[level]}`;
  const { docs } = rules[name].meta;
  return `- \`legion/${name}\` (${LEVEL_NOTE[level]}) — ${docs.description}`;
};

export interface BlockInput {
  config: LegionConfig;
  lintCommand: string;
  componentCap: number | false;
}

const enforcedRules = (config: LegionConfig): string[] =>
  Object.entries(config.levels)
    .filter(([, level]) => level > 0)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, level]) => ruleLine(name, level));

const lockedSection = (config: LegionConfig): string[] => {
  if (config.locked.length === 0) return [];
  return [
    '',
    'Locked rules. A disable naming one of these is itself a violation:',
    config.locked
      .sort()
      .map((name) => `\`${name}\``)
      .join(', '),
  ];
};

const capSection = (cap: number | false): string[] => {
  if (cap === false) return [];
  return [
    '',
    `Components are capped at ${cap} lines. Reaching it means logic leaked into the component; move it into a \`use<Component>\` hook rather than splitting the file to fit.`,
  ];
};

export const renderBlock = (input: BlockInput): string => {
  const lines = [
    START,
    '',
    '# Enforced here',
    '',
    "Generated by `legion-steer` from this repo's resolved lint config. Do not edit by hand; run `legion-steer init` to regenerate. Reasoning for every rule lives in LEGION-STANDARDS.md, which this block deliberately does not reproduce.",
    '',
    ...enforcedRules(input.config),
    ...lockedSection(input.config),
    ...capSection(input.componentCap),
    '',
    '## Bypasses',
    '',
    'A bypass is `eslint-disable-next-line <rule> -- <reason>` on the one line that needs it. Nothing else is accepted: no file-wide disable, no unnamed rule, no missing reason.',
    '',
    '## Changing what is enforced',
    '',
    'Levels live in `defineLegionConfig`, not in directives. To stop fighting a rule, propose a level change or declare a boundary path, and ask before lowering one. `legion-audit` prints the current scorecard and the nudges.',
    '',
    `Lint with \`${input.lintCommand}\`.`,
    '',
    END,
  ];
  return lines.join('\n');
};

export const severityOf = (level: Level): string => levelToSeverity(level);
