import { yarnFlavorFrom } from './toolchain.js';

const BERRY_HEAD =
  '# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!\n';
const CLASSIC_HEAD =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n';

describe('yarnFlavorFrom', () => {
  it('reads classic straight off the lockfile header', () => {
    expect(yarnFlavorFrom(CLASSIC_HEAD, undefined, false)).toBe('classic');
  });

  it('calls a classic lockfile classic even when a yarnrc.yml is lying around', () => {
    expect(yarnFlavorFrom(CLASSIC_HEAD, 'yarn@4.18.0', true)).toBe('classic');
  });

  it('reads berry from the lockfile header plus a yarnrc.yml', () => {
    expect(yarnFlavorFrom(BERRY_HEAD, 'yarn@4.18.0', true)).toBe('berry');
  });

  it('falls back to the packageManager field when there is no lockfile', () => {
    expect(yarnFlavorFrom('', 'yarn@4.18.0', false)).toBe('berry');
    expect(yarnFlavorFrom('', 'yarn@1.22.22', false)).toBe('classic');
  });

  it('is unknown with nothing to go on', () => {
    expect(yarnFlavorFrom('', undefined, false)).toBe('unknown');
  });
});
