import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { detectReactCompiler, yarnFlavorFrom } from './toolchain.js';

const BERRY_HEAD =
  '# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!\n';
const CLASSIC_HEAD =
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n';

describe('yarnFlavorFrom', () => {
  it('reads classic straight off the lockfile header', () => {
    expect(yarnFlavorFrom(CLASSIC_HEAD, undefined, false)).toBe('classic');
  });

  it('calls a classic lockfile classic even when a yarnrc.yml is lying around', () => {
    expect(yarnFlavorFrom(CLASSIC_HEAD, 'yarn@4.18.0', true)).toBe('classic');
  });

  it('reads berry from the lockfile header plus a yarnrc.yml', () => {
    expect(yarnFlavorFrom(BERRY_HEAD, 'yarn@4.18.0', true)).toBe('berry');
  });

  it('falls back to the packageManager field when there is no lockfile', () => {
    expect(yarnFlavorFrom('', 'yarn@4.18.0', false)).toBe('berry');
    expect(yarnFlavorFrom('', 'yarn@1.22.22', false)).toBe('classic');
  });

  it('is unknown with nothing to go on', () => {
    expect(yarnFlavorFrom('', undefined, false)).toBe('unknown');
  });
});

describe('detectReactCompiler', () => {
  const repo = (files: Record<string, string>): string => {
    const root = mkdtempSync(join(tmpdir(), 'legion-rc-'));
    for (const [name, contents] of Object.entries(files)) {
      writeFileSync(join(root, name), contents);
    }
    return root;
  };

  it('finds the babel plugin in devDependencies', () => {
    const root = repo({
      'package.json': JSON.stringify({
        devDependencies: { 'babel-plugin-react-compiler': '^1.0.0' },
      }),
    });
    expect(detectReactCompiler(root)).toBe(true);
  });

  it('finds it enabled in a next config', () => {
    const root = repo({
      'package.json': JSON.stringify({ dependencies: { next: '^15.0.0' } }),
      'next.config.mjs':
        'export default { experimental: { reactCompiler: true } };',
    });
    expect(detectReactCompiler(root)).toBe(true);
  });

  it('does not infer it from the React version, because 19 does not imply it', () => {
    const root = repo({
      'package.json': JSON.stringify({ dependencies: { react: '^19.0.0' } }),
    });
    expect(detectReactCompiler(root)).toBe(false);
  });
});
